-- CreateTable
CREATE TABLE `Feedback` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NOT NULL,
    `contactMethod` VARCHAR(191) NOT NULL,
    `shopsPriceco` BOOLEAN NOT NULL,
    `shopsSafeway` BOOLEAN NOT NULL,
    `shopsSavemart` BOOLEAN NOT NULL,
    `shopsCostuless` BOOLEAN NOT NULL,
    `shopsWalmart` BOOLEAN NOT NULL,
    `onlineOrdering` BOOLEAN NOT NULL,
    `usesCoupons` BOOLEAN NOT NULL,
    `awareSeniorDiscount` BOOLEAN NOT NULL,
    `triedRecipes` BOOLEAN NOT NULL,
    `ratingDeli` INTEGER NOT NULL,
    `ratingMeat` INTEGER NOT NULL,
    `ratingSeafood` INTEGER NOT NULL,
    `ratingBakery` INTEGER NOT NULL,
    `ratingDairy` INTEGER NOT NULL,
    `ratingProduce` INTEGER NOT NULL,
    `ratingFrozen` INTEGER NOT NULL,
    `ratingFloral` INTEGER NOT NULL,
    `ratingStaff` INTEGER NOT NULL,
    `ratingCheckout` INTEGER NOT NULL,
    `comments` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
