FROM node:18-alpine as builder

ARG SENTRY_DSN
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG SENTRY_AUTH_TOKEN
ARG NUXT_PUBLIC_STRAPI_URL
ARG NUXT_MAILGUN_API_KEY
ARG NUXT_TURNSTILE_SECRET_KEY
ARG SENTRY_RELEASE_NAME
ENV SENTRY_DSN=${SENTRY_DSN}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_PROJECT=${SENTRY_PROJECT}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV SENTRY_RELEASE_NAME=${SENTRY_RELEASE_NAME}
ENV NUXT_PUBLIC_STRAPI_URL=${NUXT_PUBLIC_STRAPI_URL}
ENV NUXT_MAILGUN_API_KEY=${NUXT_MAILGUN_API_KEY}
ENV NUXT_TURNSTILE_SECRET_KEY=${NUXT_TURNSTILE_SECRET_KEY}

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npm run build


FROM node:18-alpine

ARG SENTRY_DSN
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG SENTRY_AUTH_TOKEN
ARG NUXT_PUBLIC_STRAPI_URL
ARG NUXT_MAILGUN_API_KEY
ARG NUXT_TURNSTILE_SECRET_KEY
ARG SENTRY_RELEASE_NAME
ENV SENTRY_DSN=${SENTRY_DSN}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_PROJECT=${SENTRY_PROJECT}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV SENTRY_RELEASE_NAME=${SENTRY_RELEASE_NAME}
ENV NUXT_PUBLIC_STRAPI_URL=${NUXT_PUBLIC_STRAPI_URL}
ENV NUXT_MAILGUN_API_KEY=${NUXT_MAILGUN_API_KEY}
ENV NUXT_TURNSTILE_SECRET_KEY=${NUXT_TURNSTILE_SECRET_KEY}
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.output ./.output
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["npm", "run", "migrate:start"]
