-- AlterTable
ALTER TABLE `Feedback` MODIFY `email` VARCHAR(191) NULL,
    MODIFY `phone` VARCHAR(191) NULL,
    MODIFY `contactMethod` VARCHAR(191) NULL,
    MODIFY `shopsPriceco` BOOLEAN NULL,
    MODIFY `shopsSafeway` BOOLEAN NULL,
    MODIFY `shopsSavemart` BOOLEAN NULL,
    MODIFY `shopsCostuless` BOOLEAN NULL,
    MODIFY `shopsWalmart` BOOLEAN NULL,
    MODIFY `onlineOrdering` BOOLEAN NULL,
    MODIFY `usesCoupons` BOOLEAN NULL,
    MODIFY `awareSeniorDiscount` BOOLEAN NULL,
    MODIFY `triedRecipes` BOOLEAN NULL,
    MODIFY `ratingDeli` INTEGER NULL,
    MODIFY `ratingMeat` INTEGER NULL,
    MODIFY `ratingSeafood` INTEGER NULL,
    MODIFY `ratingBakery` INTEGER NULL,
    MODIFY `ratingDairy` INTEGER NULL,
    MODIFY `ratingProduce` INTEGER NULL,
    MODIFY `ratingFrozen` INTEGER NULL,
    MODIFY `ratingFloral` INTEGER NULL,
    MODIFY `ratingStaff` INTEGER NULL,
    MODIFY `ratingCheckout` INTEGER NULL,
    MODIFY `comments` VARCHAR(191) NULL;
