name: Build and Deploy Docker Image

on:
    push:
        branches: ['main']

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Prisma Generation & Migration
              run: npx prisma generate && npx prisma migrate deploy
              env:
                DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
                SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL_PRODUCTION }}

            - name: Preset Image Name
              run: echo "IMAGE_URL=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_ENV

            - name: Set short SHA
              id: sha
              run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

            - name: Build and push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                    ${{ env.IMAGE_URL }}:${{ steps.sha.outputs.sha_short }}
                    ${{ env.IMAGE_URL }}:latest
                  build-args: |
                    SENTRY_DSN=${{ vars.SENTRY_DSN }}
                    SENTRY_ORG=${{ vars.SENTRY_ORG }}
                    SENTRY_PROJECT=${{ vars.SENTRY_PROJECT }}
                    SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
                    NUXT_MAILGUN_API_KEY=${{ secrets.NUXT_MAILGUN_API_KEY }}
                    NUXT_TURNSTILE_SECRET_KEY=${{ secrets.NUXT_TURNSTILE_SECRET_KEY }}

            - name: Deploy Image to CapRrover
              uses: caprover/deploy-from-github@v1.1.2
              with:
                  server: '${{ secrets.CAPROVER_SERVER }}'
                  app: '${{ secrets.APP_NAME }}'
                  token: '${{ secrets.APP_TOKEN }}'
                  image: ${{ env.IMAGE_URL }}:latest
